### ISSUE TITLE
Exception - DFlash drafter (qwen3_dflash.py:508) + flash_attn + prompts with tools

### ISSUE THREAD

**Issue by memuxmx-ui** [AEON-7/Qwen3.6-27B-AEON-Ultimate-Uncensored-DFlash#7]
If the client wants to use tools it crashes.

DFlash drafter (qwen3_dflash.py:508) + flash_attn + prompts with tools

 RuntimeError: block_table must have shape (batch_size, max_num_blocks_per_seq)
    en  flash_attn_varlen_func
    en  vllm/model_executor/models/qwen3_dflash.py:508 forward()
--------------------------------------

ERROR 05-10 19:47:09 [dump_input.py:72] Dumping input data for V1 LLM engine (v0.20.2rc1.dev166+gf6490a284) with config: model='/models/xs', speculative_config=SpeculativeConfig(method='dflash', model='/models/dflash-drafter', num_spec_tokens=4), tokenizer='/models/xs', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=256000, download_dir=None, load_format=safetensors, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=modelopt_fp4, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='qwen3', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=aeon-ultimate, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '/root/.cache/vllm/torch_compile_cache/cf40f82d1b', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [32768], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [5, 10, 20, 25, 35, 40, 50, 60, 65, 75, 80, 90, 100, 105, 115, 120, 130, 140, 145, 155, 160], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'fuse_act_padding': False}, 'max_cudagraph_capture_size': 160, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': '/root/.cache/vllm/torch_compile_cache/cf40f82d1b/rank_0_0/eagle_head', 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=False, moe_backend='auto'), 
(EngineCore pid=168) ERROR 05-10 19:47:09 [dump_input.py:79] Dumping scheduler output for model execution: SchedulerOutput(scheduled_new_reqs=[], scheduled_cached_reqs=CachedRequestData(req_ids=['chatcmpl-b2f1f16023503b46-83d64131', 'chatcmpl-a0ee2d44f5bef104-8fc1802f', 'chatcmpl-b73d6177347d70ed-978fc053'],resumed_req_ids=set(),new_token_ids_lens=[],all_token_ids_lens={},new_block_ids=[None, None, None],num_computed_tokens=[98831, 58761, 10796],num_output_tokens=[11, 7, 6]), num_scheduled_tokens={chatcmpl-b73d6177347d70ed-978fc053: 5, chatcmpl-b2f1f16023503b46-83d64131: 5, chatcmpl-a0ee2d44f5bef104-8fc1802f: 5}, total_num_scheduled_tokens=15, scheduled_spec_decode_tokens={chatcmpl-b2f1f16023503b46-83d64131: [-1, -1, -1, -1], chatcmpl-b73d6177347d70ed-978fc053: [-1, -1, -1, -1], chatcmpl-a0ee2d44f5bef104-8fc1802f: [-1, -1, -1, -1]}, scheduled_encoder_inputs={}, num_common_prefix_blocks=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], finished_req_ids=[], free_encoder_mm_hashes=[], preempted_req_ids=[], has_structured_output_requests=false, pending_structured_output_tokens=false, num_invalid_spec_tokens=null, kv_connector_metadata=null, ec_connector_metadata=null, new_block_ids_to_zero=null)
(EngineCore pid=168) ERROR 05-10 19:47:09 [dump_input.py:81] Dumping scheduler stats: SchedulerStats(num_running_reqs=3, num_waiting_reqs=0, num_skipped_waiting_reqs=0, step_counter=0, current_wave=0, kv_cache_usage=0.5327686134641105, prefix_cache_stats=PrefixCacheStats(reset=False, requests=0, queries=0, hits=0, preempted_requests=0, preempted_queries=0, preempted_hits=0), connector_prefix_cache_stats=None, kv_cache_eviction_events=[], spec_decoding_stats=None, kv_connector_stats=None, waiting_lora_adapters={}, running_lora_adapters={}, cudagraph_stats=None, perf_stats=None)
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138] EngineCore encountered a fatal error.
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138] Traceback (most recent call last):
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1129, in run_engine_core
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     engine_core.run_busy_loop()
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1170, in run_busy_loop
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     self._process_engine_step()
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1209, in _process_engine_step
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     outputs, model_executed = self.step_fn()
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]                               ^^^^^^^^^^^^^^
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 473, in step_with_batch_queue
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     exec_future = self.model_executor.execute_model(
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/uniproc_executor.py", line 119, in execute_model
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     output.result()
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     return self.__get_result()
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]            ^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     raise self._exception
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/uniproc_executor.py", line 97, in collective_rpc
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     result = run_method(self.driver_worker, method, args, kwargs)
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/serial_utils.py", line 510, in run_method
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     return func(*args, **kwargs)
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/worker_base.py", line 337, in execute_model
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     return self.worker.execute_model(scheduler_output)
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     return func(*args, **kwargs)
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 843, in execute_model
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     output = self.model_runner.execute_model(
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     return func(*args, **kwargs)
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 4030, in execute_model
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     deferred_state_corrections_fn()
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 1432, in correct_spec_decode_token_counts
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]     num_accepted = valid_sampled_token_count[prev_req_index] - 1
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138]                    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
(EngineCore pid=168) ERROR 05-10 19:47:09 [core.py:1138] IndexError: list index out of range
(EngineCore pid=168) Process EngineCore:
(EngineCore pid=168) Traceback (most recent call last):
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1140, in run_engine_core
(EngineCore pid=168)     raise e
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1129, in run_engine_core
(EngineCore pid=168)     engine_core.run_busy_loop()
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1170, in run_busy_loop
(EngineCore pid=168)     self._process_engine_step()
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1209, in _process_engine_step
(EngineCore pid=168)     outputs, model_executed = self.step_fn()
(EngineCore pid=168)                               ^^^^^^^^^^^^^^
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 473, in step_with_batch_queue
(EngineCore pid=168)     exec_future = self.model_executor.execute_model(
(EngineCore pid=168)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/uniproc_executor.py", line 119, in execute_model
(EngineCore pid=168)     output.result()
(EngineCore pid=168)   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
(EngineCore pid=168)     return self.__get_result()
(EngineCore pid=168)            ^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168)   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
(EngineCore pid=168)     raise self._exception
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/uniproc_executor.py", line 97, in collective_rpc
(EngineCore pid=168)     result = run_method(self.driver_worker, method, args, kwargs)
(EngineCore pid=168)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/serial_utils.py", line 510, in run_method
(EngineCore pid=168)     return func(*args, **kwargs)
(EngineCore pid=168)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/worker_base.py", line 337, in execute_model
(EngineCore pid=168)     return self.worker.execute_model(scheduler_output)
(EngineCore pid=168)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
(EngineCore pid=168)     return func(*args, **kwargs)
(EngineCore pid=168)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 843, in execute_model
(EngineCore pid=168)     output = self.model_runner.execute_model(
(EngineCore pid=168)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 124, in decorate_context
(EngineCore pid=168)     return func(*args, **kwargs)
(EngineCore pid=168)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 4030, in execute_model
(EngineCore pid=168)     deferred_state_corrections_fn()
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 1432, in correct_spec_decode_token_counts
(EngineCore pid=168)     num_accepted = valid_sampled_token_count[prev_req_index] - 1
(EngineCore pid=168)                    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
(EngineCore pid=168) IndexError: list index out of range
(EngineCore pid=168) 
(EngineCore pid=168) During handling of the above exception, another exception occurred:
(EngineCore pid=168) 
(EngineCore pid=168) Traceback (most recent call last):
(EngineCore pid=168)   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore pid=168)     self.run()
(EngineCore pid=168)   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
(EngineCore pid=168)     self._target(*self._args, **self._kwargs)
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1147, in run_engine_core
(EngineCore pid=168)     engine_core.shutdown()
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 574, in shutdown
(EngineCore pid=168)     self.model_executor.shutdown()
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/uniproc_executor.py", line 142, in shutdown
(EngineCore pid=168)     worker.shutdown()
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/worker_base.py", line 212, in shutdown
(EngineCore pid=168)     self.worker.shutdown()
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 1115, in shutdown
(EngineCore pid=168)     model_runner.shutdown()
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 6022, in shutdown
(EngineCore pid=168)     self._cleanup_profiling_kv_cache()
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 6030, in _cleanup_profiling_kv_cache
(EngineCore pid=168)     torch.accelerator.synchronize()
(EngineCore pid=168)   File "/usr/local/lib/python3.12/dist-packages/torch/accelerator/__init__.py", line 263, in synchronize
(EngineCore pid=168)     torch._C._accelerator_synchronizeDevice(device_index)
(EngineCore pid=168) torch.AcceleratorError: CUDA error: device-side assert triggered
(EngineCore pid=168) Search for `cudaErrorAssert' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
(EngineCore pid=168) CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(EngineCore pid=168) For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(EngineCore pid=168) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(EngineCore pid=168) 
(APIServer pid=1) ERROR 05-10 19:47:09 [async_llm.py:704] AsyncLLM output_handler failed.
(APIServer pid=1) ERROR 05-10 19:47:09 [async_llm.py:704] Traceback (most recent call last):
(APIServer pid=1) ERROR 05-10 19:47:09 [async_llm.py:704]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 660, in output_handler
(APIServer pid=1) ERROR 05-10 19:47:09 [async_llm.py:704]     outputs = await engine_core.get_output_async()
(APIServer pid=1) ERROR 05-10 19:47:09 [async_llm.py:704]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=1) ERROR 05-10 19:47:09 [async_llm.py:704]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 998, in get_output_async
(APIServer pid=1) ERROR 05-10 19:47:09 [async_llm.py:704]     raise self._format_exception(outputs) from None
(APIServer pid=1) ERROR 05-10 19:47:09 [async_llm.py:704] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984] Error in chat completion stream generator.
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984] Traceback (most recent call last):
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/chat_completion/serving.py", line 487, in chat_completion_stream_generator
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     async for res in result_generator:
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 579, in generate
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     out = q.get_nowait() or await q.get()
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]                             ^^^^^^^^^^^^^
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/output_processor.py", line 88, in get
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     raise output
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 660, in output_handler
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     outputs = await engine_core.get_output_async()
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 998, in get_output_async
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     raise self._format_exception(outputs) from None
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984] Error in chat completion stream generator.
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984] Traceback (most recent call last):
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/chat_completion/serving.py", line 487, in chat_completion_stream_generator
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     async for res in result_generator:
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 579, in generate
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     out = q.get_nowait() or await q.get()
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]                             ^^^^^^^^^^^^^
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/output_processor.py", line 88, in get
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     raise output
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/chat_completion/serving.py", line 487, in chat_completion_stream_generator
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     async for res in result_generator:
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 579, in generate
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     out = q.get_nowait() or await q.get()
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]                             ^^^^^^^^^^^^^
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/output_processor.py", line 88, in get
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     raise output
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 660, in output_handler
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     outputs = await engine_core.get_output_async()
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 998, in get_output_async
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     raise self._format_exception(outputs) from None
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984] Error in chat completion stream generator.
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984] Traceback (most recent call last):
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/chat_completion/serving.py", line 487, in chat_completion_stream_generator
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     async for res in result_generator:
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 579, in generate
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     out = q.get_nowait() or await q.get()
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]                             ^^^^^^^^^^^^^
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/output_processor.py", line 88, in get
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     raise output
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/chat_completion/serving.py", line 487, in chat_completion_stream_generator
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     async for res in result_generator:
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 579, in generate
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     out = q.get_nowait() or await q.get()
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]                             ^^^^^^^^^^^^^
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/output_processor.py", line 88, in get
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     raise output
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/chat_completion/serving.py", line 487, in chat_completion_stream_generator
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     async for res in result_generator:
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 579, in generate
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     out = q.get_nowait() or await q.get()
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]                             ^^^^^^^^^^^^^
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/output_processor.py", line 88, in get
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     raise output
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 660, in output_handler
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     outputs = await engine_core.get_output_async()
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 998, in get_output_async
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984]     raise self._format_exception(outputs) from None
(APIServer pid=1) ERROR 05-10 19:47:09 [serving.py:984] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.

**Comment by memuxmx-ui** [comment]
docker run -d \
  --name "${CONTAINER_NAME}" \
  --restart unless-stopped \
  --gpus all \
  --network host \
  --ipc=host \
  --ulimit memlock=-1 \
  -v "${MODEL_DIR}:/models/xs" \
  -v "${DRAFTER_DIR}:/models/dflash-drafter" \
  -e VLLM_ALLOW_LONG_MAX_MODEL_LEN=1 \
  -e TORCH_CUDA_ARCH_LIST=12.1a \
  -e PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
  -e TORCH_MATMUL_PRECISION=high \
  -e NVIDIA_FORWARD_COMPAT=1 \
  -e NVIDIA_DISABLE_REQUIRE=1 \
  -e ENABLE_NVFP4_SM100=0 \
  -e VLLM_USE_FLASHINFER_MOE_FP4=0 \
  -e VLLM_TEST_FORCE_FP8_MARLIN=0 \
  -e VLLM_USE_FLASHINFER_SAMPLER=1 \
  -e VLLM_NVFP4_GEMM_BACKEND=flashinfer-cutlass \
  ghcr.io/aeon-7/vllm-aeon-ultimate-dflash:qwen36-v4 \
  bash -c "exec vllm serve /models/xs \
    --served-model-name aeon-ultimate qwen36-ultimate aeon-fast aeon-deep aeon-ultimate-xs \
    --host 0.0.0.0 --port ${PORT} \
    --tensor-parallel-size 1 \
    --dtype auto \
    --quantization modelopt \
    --kv-cache-dtype auto \
    --max-model-len 256000 \
    --max-num-seqs 16 \
    --max-num-batched-tokens 32768 \
    --gpu-memory-utilization 0.85 \
    --enable-chunked-prefill \
    --enable-prefix-caching \
    --generation-config vllm \
    --load-format safetensors \
    --trust-remote-code \
    --enable-auto-tool-choice \
    --tool-call-parser qwen3_xml \
    --reasoning-parser qwen3 \
    --attention-backend flash_attn \
    --limit-mm-per-prompt '{\"image\": 4, \"video\": 2}' \
    --mm-encoder-tp-mode data \
    --mm-processor-cache-type shm \
    --mm-shm-cache-max-object-size-mb 256 \
    --speculative-config '{\"method\":\"dflash\",\"model\":\"/models/dflash-drafter\",\"num_speculative_tokens\":4}'"

**Comment by aider4ryder** [comment]
Additional data point from a newer `aeon-vllm-ultimate:latest` image: this still reproduces on a GB10 deployment even though the image labels say it includes the PR #40898/#41703 DFlash overlays.

This was discovered during a real deployment by a Hermes Agent driven by `gpt-5.5-xhigh`, while serving Hermes Agent and other OpenAI-compatible agent applications that use tool schemas.

## What is different from the original report

- Image digest: `ghcr.io/aeon-7/aeon-vllm-ultimate@sha256:09c83deefe68fd1f37b6d776900870f53dd31763c4b18b869495d6a968827ff9`
- Image labels include:
  - `aeon.base=v0.22.2+pr44389.aeon (main@2026-06-05)`
  - `aeon.layer=pr41703+pr40898 merged 2026-06-11`
  - `aeon.fixes=dflash-swa,rejected-ctx-slot-mask,gemma4-embed-norm,gemma4-softcap,flashattn-drafter`
- vLLM runtime reports: `v0.22.1+pr44389.aeon`
- Tool parser was `qwen3_coder`, not `qwen3_xml`.
- Crash happened with only `num_running_reqs=3` and `kv_cache_usage=0.1886`, so this does not look like a full-KV-cache condition.

## Launch configuration excerpt

```bash
vllm serve /models/aeon-cache/snapshots/6394b93fa092dcbfbf09e952f56f30337509d17c \
  --served-model-name "aeon-ultimate" "qwen3.6-27b-decensor-by-aeon" \
  --kv-cache-dtype auto \
  --max-model-len 262144 \
  --max-num-seqs 8 \
  --max-num-batched-tokens 8192 \
  --gpu-memory-utilization 0.47 \
  --enable-prefix-caching \
  --enable-chunked-prefill \
  --speculative-config '{"method":"dflash","model":"/models/dflash-cache/snapshots/0919688658996800f86b895034249700e9481106","num_speculative_tokens":4,"attention_backend":"flash_attn"}' \
  --reasoning-parser qwen3 \
  --enable-auto-tool-choice \
  --tool-call-parser qwen3_coder
```

Hardware/deployment context:

- GB10 / DGX Spark style unified-memory host.
- Model weights are ModelOpt FP4; KV cache was `auto` / BF16 in this deployment.
- OpenAI-compatible `/v1/chat/completions` endpoint used by Hermes Agent and other agent apps with tool schemas.

## Immediate pre-crash scheduler state

Right before the fatal error, logs showed 3 running requests:

```text
Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 40.1 tokens/s, Running: 3 reqs, Waiting: 0 reqs, GPU KV cache usage: 18.9%, Prefix cache hit rate: 90.7%
```

Scheduler dump:

```text
scheduled_cached_reqs=CachedRequestData(
  req_ids=[
    'chatcmpl-99d400ef883c4053-a8fc2ce6',
    'chatcmpl-b6f1ed3411ce26cc-8dd18764',
    'chatcmpl-91701b513af87267-924b2cf2'
  ],
  new_block_ids=[None, None, None],
  num_computed_tokens=[847, 28373, 344],
  num_output_tokens=[504, 350, 1]
)
num_scheduled_tokens={
  chatcmpl-99d400ef883c4053-a8fc2ce6: 5,
  chatcmpl-b6f1ed3411ce26cc-8dd18764: 5,
  chatcmpl-91701b513af87267-924b2cf2: 5
}
total_num_scheduled_tokens=15
scheduled_spec_decode_tokens={
  chatcmpl-91701b513af87267-924b2cf2: [-1, -1, -1, -1],
  chatcmpl-99d400ef883c4053-a8fc2ce6: [-1, -1, -1, -1],
  chatcmpl-b6f1ed3411ce26cc-8dd18764: [-1, -1, -1, -1]
}
SchedulerStats(num_running_reqs=3, num_waiting_reqs=0, kv_cache_usage=0.1885745978924016, ...)
```

## Fatal stack excerpt

```text
EngineCore encountered a fatal error.
...
File "/usr/local/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 4492, in sample_tokens
  propose_draft_token_ids(sampled_token_ids)
File "/usr/local/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 4454, in propose_draft_token_ids
  self._draft_token_ids = self.propose_draft_token_ids(...)
File "/usr/local/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 5064, in propose_draft_token_ids
  draft_token_ids = self.drafter.propose(...)
File "/usr/local/lib/python3.12/site-packages/vllm/v1/spec_decode/llm_base_proposer.py", line 503, in propose
  ret_hidden_states = self.model(**model_kwargs)
File "/usr/local/lib/python3.12/site-packages/vllm/model_executor/models/qwen3_dflash.py", line 637, in forward
  return self.model(input_ids, positions, inputs_embeds)
File "/usr/local/lib/python3.12/site-packages/vllm/model_executor/layers/attention/attention.py", line 758, in unified_attention_with_output
  self.impl.forward(...)
File "/usr/local/lib/python3.12/site-packages/vllm/v1/attention/backends/flash_attn.py", line 796, in forward
  flash_attn_varlen_func(...)
File "/usr/local/lib/python3.12/site-packages/vllm/vllm_flash_attn/flash_attn_interface.py", line 300, in flash_attn_varlen_func
  out, softmax_lse = torch.ops._vllm_fa2_C.varlen_fwd(...)
RuntimeError: block_table must have shape (batch_size, max_num_blocks_per_seq)
```

After this, the API server returned 500 for in-flight chat completions and the service exited failed.

## Question / help requested

Because this reproduces on an image that already advertises the #40898/#41703 overlays, what is the recommended production workaround for Qwen3.6 DFlash + `flash_attn` + OpenAI tool/agent workloads?

Specific questions:

1. Is this expected to be fixed by a newer image/tag than `sha256:09c83...`?
2. Is `qwen3_coder` vs `qwen3_xml` relevant to this crash, or is the parser only incidental and the root cause is DFlash/FlashAttention batching metadata?
3. Is the recommended mitigation to cap text-LLM concurrency to 1 for tool-heavy requests?
4. Would disabling DFlash/speculative decoding for agent/tool workloads be the safest temporary workaround?
5. Are there known safer settings for this combination, e.g. disabling prefix caching/chunked prefill, lowering `max_num_seqs`, or using a different drafter attention backend?

Thanks — happy to provide more logs if useful, but the key point is that the same `block_table` crash still appears on the post-2026-06-11 `latest` image with the DFlash overlay labels present.

**Comment by AEON-7** [comment]
Thanks for the detailed logs — especially aider4ryder's image-digest and label dump, which is what makes this diagnosable.

There are actually two different crashes here, and both are on pre-fix images. The current `ghcr.io/aeon-7/aeon-vllm-ultimate:latest` already carries the fixes.

**1. The newer reproduction (the real `block_table must have shape` crash).** Your traceback at `qwen3_dflash.py:637 -> flash_attn_varlen_func` is the padded-vs-unpadded DFlash drafter KV block-table shape mismatch. We fixed it by porting upstream PR #43982 (that PR fixed MTP but never touched DFlash). The catch is your digest: you're on `sha256:09c83d...`, which reports runtime `v0.22.1+pr44389.aeon` with labels `aeon.layer=pr41703+pr40898 merged 2026-06-11`. That is the **`:2026-06-11-pr41703` image — the one BEFORE the block-table fix.** The #43982 port only landed in `:2026-06-18-v0.23.0-dflashfix` (what `:latest` should point to now). So `:latest` on your host resolved to, or is pinned to, a stale digest.

Fix:
```bash
docker pull ghcr.io/aeon-7/aeon-vllm-ultimate:latest   # force re-pull
# then verify you actually got the fixed build:
docker inspect ghcr.io/aeon-7/aeon-vllm-ultimate:latest \
  --format '{{index .Config.Labels "aeon.base"}} | {{index .Config.Labels "aeon.fixes"}}'
```
You want `aeon.base` to read `v0.23.0` and `aeon.fixes` to include `dflash-blocktable`. The runtime banner should say `v0.23.0+aeon`, not `v0.22.1`. If you'd rather not chase `:latest`, pin the dated tag `:2026-06-18-v0.23.0-dflashfix`.

**2. The original report (qwen36-v4).** That title says block_table, but the dumped fatal trace is actually `correct_spec_decode_token_counts -> valid_sampled_token_count[prev_req_index] - 1 -> IndexError` plus a CUDA device-side assert, on `v0.20.2rc1` in the retired `qwen36-v4` container. That per-revision lineage (`v3/v4/v5`) is superseded — the rebuilt 0.23.0 spec-decode path resolves that family too. Just move to the unified image.

**Answers to your specific questions:**
1. Yes — fixed by a newer image than `sha256:09c83...`. Use `:2026-06-18-v0.23.0-dflashfix` / a freshly-pulled `:latest`.
2. `qwen3_coder` vs `qwen3_xml` is incidental. Root cause is the DFlash/FlashAttention block-table metadata, not the parser. (`qwen3_coder` is the documented parser for this model.)
3. Not necessary on the fixed image — it scales cleanly to c=64.
4. Disabling DFlash would work as a stopgap, but you don't need to; just upgrade the image.
5. Two config items to fix while you're at it, independent of the image: (a) set `num_speculative_tokens:10`, not `4` — 10 is the validated default. (b) Remove `"attention_backend":"flash_attn"` from inside the `--speculative-config` JSON; the drafter backend should be left at default — adding it is documented as a do-not. Keep `--max-num-seqs <= 16` (you're at 8, fine) and BF16 KV (your `auto` is fine).

Once you're on the freshly-pulled `:latest` with `n=10` and no injected drafter backend, this combination (DFlash + flash_attn + OpenAI tool schemas) is the benchmarked production path. Please reopen with the new runtime banner + label dump if it still reproduces.

---
*📝 Update — the README now has a [symptom-keyed **Troubleshooting** section](https://github.com/AEON-7/Qwen3.6-27B-AEON-Ultimate-Uncensored-DFlash#troubleshooting) that covers this exact signature, and **n=10** is pinned as the stable default. That's the canonical reference going forward.*
